<h1 style="font-size:30px;">Numpy Refresher (Part-3)</h1>

- Element Wise Operations
- Linear Algebra
- Array Statistics


<img src='https://learnopencv.com/wp-content/uploads/2022/01/c4_01_NumPy_logo.png' width=200 align='left'><br/>

In [1]:
import numpy as np

def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}'.format(array.shape))
    print('Array Dim:\t{}\n'.format(array.ndim))

## 1 Element-Wise Operations


Let's generate two random arrays to demonstrate element-wise operations. 

In [2]:
a = np.random.random((4,4))
b = np.random.random((4,4))
array_info(a)
array_info(b)

Array:
[[0.59000455 0.10495251 0.55007971 0.6634643 ]
 [0.00516332 0.9074339  0.57376291 0.30862948]
 [0.60270497 0.8801744  0.4460596  0.16934236]
 [0.31788964 0.7541939  0.23443211 0.23092295]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array:
[[0.19271715 0.04144996 0.55729259 0.70439969]
 [0.61198913 0.20241261 0.09905048 0.84313058]
 [0.62974494 0.41398208 0.25663903 0.50028052]
 [0.56171641 0.98966393 0.8323056  0.59274444]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2



### 1.1 Element-Wise Scalar Operations

### <font style="color:rgb(50,120,230)">Scalar Addition</font>

In [3]:
a + 5 # Element wise scalar addition.

array([[5.59000455, 5.10495251, 5.55007971, 5.6634643 ],
       [5.00516332, 5.9074339 , 5.57376291, 5.30862948],
       [5.60270497, 5.8801744 , 5.4460596 , 5.16934236],
       [5.31788964, 5.7541939 , 5.23443211, 5.23092295]])

### <font style="color:rgb(50,120,230)">Scalar Subtraction</font>

In [5]:
a - 5 # Element wise scalar subtraction.

array([[-4.40999545, -4.89504749, -4.44992029, -4.3365357 ],
       [-4.99483668, -4.0925661 , -4.42623709, -4.69137052],
       [-4.39729503, -4.1198256 , -4.5539404 , -4.83065764],
       [-4.68211036, -4.2458061 , -4.76556789, -4.76907705]])

### <font style="color:rgb(50,120,230)">Scalar Multiplication</font>

In [6]:
a * 10 # Element wise scalar multiplication.

array([[5.90004551, 1.04952513, 5.50079709, 6.63464299],
       [0.05163317, 9.07433895, 5.73762914, 3.08629482],
       [6.0270497 , 8.801744  , 4.46059605, 1.69342363],
       [3.17889638, 7.54193901, 2.34432113, 2.30922947]])

### <font style="color:rgb(50,120,230)">Scalar Division</font>

In [7]:
a/10 # Element wise scalar division.

array([[0.05900046, 0.01049525, 0.05500797, 0.06634643],
       [0.00051633, 0.09074339, 0.05737629, 0.03086295],
       [0.0602705 , 0.08801744, 0.04460596, 0.01693424],
       [0.03178896, 0.07541939, 0.02344321, 0.02309229]])

### 1.2 Element-Wise Array Operations

### <font style="color:rgb(50,120,230)">Array Addition</font>

In [8]:
a + b # Element wise array/vector addition.

array([[0.7827217 , 0.14640247, 1.1073723 , 1.36786399],
       [0.61715245, 1.1098465 , 0.6728134 , 1.15176007],
       [1.23244991, 1.29415648, 0.70269863, 0.66962288],
       [0.87960605, 1.74385783, 1.06673772, 0.82366739]])

### <font style="color:rgb(50,120,230)">Array Subtraction</font>

In [9]:
a - b # Element wise array/vector subtraction.

array([[ 0.3972874 ,  0.06350255, -0.00721288, -0.04093539],
       [-0.60682581,  0.70502129,  0.47471243, -0.5345011 ],
       [-0.02703997,  0.46619232,  0.18942058, -0.33093816],
       [-0.24382677, -0.23547003, -0.59787349, -0.36182149]])

### <font style="color:rgb(50,120,230)">Array Multiplication</font>

In [10]:
a * b # Element wise array/vector multiplication.

array([[0.11370399, 0.00435028, 0.30655535, 0.46734404],
       [0.00315989, 0.18367606, 0.05683149, 0.26021496],
       [0.3795504 , 0.36437643, 0.1144763 , 0.08471869],
       [0.17856383, 0.7463985 , 0.19511916, 0.13687829]])

### <font style="color:rgb(50,120,230)">Array Division</font>

In [11]:
a / b # element wise array/vector division

array([[3.0615052 , 2.53202925, 0.98705728, 0.94188613],
       [0.00843694, 4.48308985, 5.79263126, 0.36605182],
       [0.95706204, 2.12611716, 1.73808173, 0.33849482],
       [0.56592549, 0.76207072, 0.28166591, 0.38958264]])

Notice that the dimension of both arrays are equal in the above array element-wise operations. **What if the dimensions are not equal.** Let's check!

In [12]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 4)
array_info(c)

# Should throw ValueError.
import traceback
try:
    a + c
except Exception:
    traceback.print_exc()

Array "a":
Array:
[[0.59000455 0.10495251 0.55007971 0.6634643 ]
 [0.00516332 0.9074339  0.57376291 0.30862948]
 [0.60270497 0.8801744  0.4460596  0.16934236]
 [0.31788964 0.7541939  0.23443211 0.23092295]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array "c":
Array:
[[0.27482982 0.62380746 0.92564048 0.67766524]
 [0.17040837 0.42568521 0.96821731 0.805421  ]]
Data type:	float64
Array shape:	(2, 4)
Array Dim:	2



Traceback (most recent call last):
  File "C:\Users\kshnt\AppData\Local\Temp\ipykernel_14544\3053537578.py", line 10, in <module>
    a + c
ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 


<font color='red'>**Oh, got the ValueError!!**</font>

What is this error?

<font color='red'>ValueError</font>: operands could not be broadcast together with shapes `(4,4)` `(2,2)` 

### 1.3 Broadcasting

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array. 

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Documentation: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html" target=_blank>broadcasting</a>

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when:

 - They are equal, or
 - One of them is 1
 
The examples below show how `B` is successfully broadcasted to `A` according to the rules above.
 
``` python
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a + b)  # b is reshaped such that it can be added to a.

# b = [0,1,0] is broadcasted to     [[0, 1, 0],
#                                    [0, 1, 0],
#                                    [0, 1, 0]]  and added to a.

Array "a":
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int32
Array shape:	(3, 3)
Array Dim:	2

Array "b":
Array:
[0 1 0]
Data type:	int32
Array shape:	(3,)
Array Dim:	1

Array "a+b":
Array:
[[1 3 3]
 [4 6 6]
 [7 9 9]]
Data type:	int32
Array shape:	(3, 3)
Array Dim:	2



## 2 Linear Algebra

In this section, we will take a look at the most commonly used linear algebra operations used in machine learning.

## 2.1 Transpose

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Either syntax below can be used:

``` python
result = np.transpose(a, axes=None)

result = a.transpose(*axes)

result = a.T
```

Returns a view of the NumPy array `a` with axes transposed.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html" target=_blank>np.transpose</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [14]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('Transose of "a":')
a_transpose = a.transpose()  # Or a.T
array_info(a_transpose)

Array "a":
Array:
[[0.00388805 0.57431544 0.11390374]
 [0.13128825 0.82559144 0.74652218]]
Data type:	float64
Array shape:	(2, 3)
Array Dim:	2

Transose of "a":
Array:
[[0.00388805 0.13128825]
 [0.57431544 0.82559144]
 [0.11390374 0.74652218]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.2 Matrix Multiplication
We will discuss two ways of performing matrix multiplication.

- `np.matmul`
- Python `@` operator

### <font style="color:rgb(50,120,230)">Using: `matmul`</font>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Using `matmul` is the most common approach for multiplying two matrices using Numpy. Multiplying two matrices requires that the number of columns of the first matrix, `M`, equals the number of rows in the second matrix, `N`, as shown below.

``` python
   M        N      
[p, q] x [q, r] = [p , r]
```
Documentation: <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html" target=_blank>np.matmul</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [15]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = np.matmul(a,b) 

print('matrix multiplication of a and b:')
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape)) # dim-1 of a and dim-0 of b has to be 
                                                          # same for matrix multiplication

Array "a":
Array:
[[0.61450926 0.02317411 0.88381983 0.45765777]
 [0.02280803 0.51901748 0.36282099 0.54985297]
 [0.68979582 0.55733893 0.87176516 0.82261643]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.39191183 0.67047728]
 [0.78564432 0.74712691]
 [0.97626218 0.20610525]
 [0.98659335 0.82169737]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

matrix multiplication of a and b:
Array:
[[1.57340205 0.98754458]
 [1.31339156 0.92965623]
 [2.37086857 1.73451247]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2

(3, 4) x (4, 2) --> (3, 2)


### <font style="color:rgb(50,120,230)">Using: `@` operator</font>

This method of multiplication was introduced in Python 3.5. <a href="https://www.python.org/dev/peps/pep-0465/" target=_blank>See docs</a>.

In [16]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = a@b 
array_info(c)

Array "a":
Array:
[[0.89917071 0.92855751 0.84510913 0.52408771]
 [0.96479465 0.67068534 0.02773653 0.21388542]
 [0.65964823 0.02031664 0.91829772 0.96743652]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.03925438 0.03574875]
 [0.89727935 0.24924441]
 [0.60899186 0.85343453]
 [0.42218206 0.86412658]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

Array:
[[1.60439688 1.43770542]
 [0.74685443 0.41015016]
 [1.01179396 1.64834   ]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.3 Matrix Inverse

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.linalg.inv(a)
```

For a square matrix, `a`, compute the (multiplicative) inverse of a matrix.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html?highlight=matrix%20inverse" target=_blank>np.linalg.inv</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [17]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)

A_inverse = np.linalg.inv(A)
print('Inverse of "A" ("A_inverse"):')
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)

Array "A":
Array:
[[0.1877801  0.51900504 0.47100914]
 [0.96076937 0.36961799 0.82478408]
 [0.03535137 0.71171664 0.47593478]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

Inverse of "A" ("A_inverse"):
Array:
[[-24.86373287   5.33519798  15.36063206]
 [-25.89238591   4.39820907  18.00241948]
 [ 40.56650154  -6.97340328 -25.96078591]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

"A x A_inverse = Identity" should be true:
Array:
[[1.00000000e+00 0.00000000e+00 1.77635684e-15]
 [7.10542736e-15 1.00000000e+00 0.00000000e+00]
 [3.55271368e-15 0.00000000e+00 1.00000000e+00]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2



### 2.4 Dot Product

The dot product between two euqal length vectors is a scalar defined by the sum of the element-wise product of the two vectors.

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.dot(a, b, out=None)
```


Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html?highlight=dot%20product" target=_blank>np.dot</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

array_info(a)
array_info(b)

dot_prod = np.dot(a, b) 
array_info(dot_prod)

Array:
[1 2 3 4]
Data type:	int32
Array shape:	(4,)
Array Dim:	1

Array:
[5 6 7 8]
Data type:	int32
Array shape:	(4,)
Array Dim:	1

Array:
70
Data type:	int32
Array shape:	()
Array Dim:	0



## 3 Array Statistics

### 3.1 Sum

In [19]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


### 3.2 Sum Along Axis

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])
array_info(a)
print('')

print('sum along axis=0: ',a.sum(axis = 0)) # Sum along axis=0 ie: 1+4, 2+5, 3+6
print("")
print('sum along axis=1: ',a.sum(axis = 1)) # Sum along axis=1 ie: 1+2+3, 4+5+6

Array:
[[1 2 3]
 [4 5 6]]
Data type:	int32
Array shape:	(2, 3)
Array Dim:	2


sum along axis=0:  [5 7 9]

sum along axis=1:  [ 6 15]


### 3.3 Minimum and Maximum

In [21]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


### 3.4 Min and Max along Axis

In [22]:
a = np.array([[-2, 0, 4], [1, 2, 3]])

array_info(a)

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

Array:
[[-2  0  4]
 [ 1  2  3]]
Data type:	int32
Array shape:	(2, 3)
Array Dim:	2

a =
 [[-2  0  4]
 [ 1  2  3]] 

Minimum =  -2
Maximum =  4

Minimum along axis 0 =  [-2  0  3]
Maximum along axis 0 =  [1 2 4]

Minimum along axis 1 =  [-2  1]
Maximum along axis 1 =  [4 3]


### 3.5 Mean and Standard Deviation

In [23]:
# Create some data.
data = np.array([1.2, 2.3, 5.0, 3.3, 1.4, 5.6])

print('Mean of the array               = {:8.6f}'.format(data.mean()))
print('Standard deviation of the array = {:8.6f}'.format(data.std()))

Mean of the array               = 3.133333
Standard deviation of the array = 1.684900


### 3.6 Standardizing an Array

Normalize the data array to have `mean=0` and `std=1`.

In [24]:
print('Array              = ', data)
print('Mean               = {:8.6f}'.format(data.mean()))
print('Standard deviation = {:8.5f}'.format(data.std()))
print()

standardized_array = (data - data.mean())/data.std()

print('Standardized Array = ', standardized_array)
print('Mean               = {:8.6f}'.format(standardized_array.mean()))  
print('Standard deviation = {:8.6f}'.format(standardized_array.std()))   

Array              =  [1.2 2.3 5.  3.3 1.4 5.6]
Mean               = 3.133333
Standard deviation = 1.684900

Standardized Array =  [-1.14744675 -0.49458912  1.10787962  0.09891782 -1.02874536  1.46398379]
Mean               = -0.000000
Standard deviation = 1.000000
